### ISSUE TITLE
Cannot call Segment.disable (Android)

### ISSUE THREAD

**Issue by fdietze** [claimsforce-gmbh/flutter-segment#10]
On Android, when I want to disable segment, I get the following error:

```
E/flutter ( 8834): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method disable on channel flutter_segment)
E/flutter ( 8834): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 8834): <asynchronous suspension>
E/flutter ( 8834): #1      SegmentMethodChannel.disable (package:flutter_segment/src/segment_method_channel.dart:101:22)
E/flutter ( 8834): #2      Segment.disable (package:flutter_segment/src/segment.dart:77:21)
```

Tracking an event from the same code position works fine.

**Comment by MaiKaY** [comment]
Hi @fdietze,
could you please try it with the latest version (`2.0.1`)

**Comment by fdietze** [comment]
Just tried it. Same error...
I can also try versions from a branch if that makes testing easier.

Thanks for your help!

**Comment by MaiKaY** [comment]
My mistake. This method isn't implemented for Android ([here](https://github.com/claimsforce-gmbh/flutter-segment/blob/master/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java#L118-L138)) yet. I adjusted the documentation for that.

@vinicius-animo Do you have time to implement the missing methods?
- `disable`
- `enable`
- `debug`

**Comment by MaiKaY** [comment]
Hi @fdietze,
could you please try it again with `2.0.2`?

**Comment by fdietze** [comment]
Thank you, it's working! :+1: 

As far as I understand, it should work now for android and iOS. Is that correct?

**Comment by MaiKaY** [comment]
Yeah. That's correct!
