### ISSUE TITLE
Platform Exception on flutter web

### ISSUE THREAD

**Issue by GeorgePag** [claimsforce-gmbh/flutter-segment#105]
Hello I get the below code when running my flutter web project
`PlatformException(Unimplemented, null, The segment plugin for web doesn't implement the method 'config', null)`
My setup is the same setup provided in segment package just these in main:
`await Segment.config(
    options: SegmentConfig(
      writeKey: 'My_Key',
      trackApplicationLifecycleEvents: true,
      amplitudeIntegrationEnabled: true,
      debug: true,
    ),
  );`

`SegmentDefaultOptions.instance.options = {
    'integrations': {
      'Amplitude': {'session_id': 'somethingRandom'}
    }
  };`

**Comment by HerrNiklasRaab** [comment]
same here!

**Comment by MaiKaY** [comment]
This project is not longer maintained from this repository. In case this issue still remains please open a new issue [here](https://github.com/la-haus/flutter-library-segment/issues).
