### ISSUE TITLE
setContext 

### ISSUE THREAD

**Issue by benjwilson10** [claimsforce-gmbh/flutter-segment#14]
Hi,

Great package and Segment is awesome!

In my segment debugger, events seem to be coming through correctly with the device information populated as below.

 "device": {
      "adTrackingEnabled": true,
      "advertisingId": "5F8DFEA2-XXXX-XXXX-XXXX-DC0AF85335F7",
      "id": "B2D8C773-XXXX-XXXX-XXXX-D7EDEE88D607",
      "manufacturer": "Apple",
      "model": "iPad8,3",
      "type": "ios"
 },

When I receive the push token from One Signal in the app, I then set Context as below.

await Segment.setContext({
  'device': {
    'token': yourTokenString
  },
});

The problem is, this overrides the device information above and replaces with this below. (This may be the desired functionality)

 "device": {
      "token": yourTokenStringr,
      "type": "ios"
 },

Is there a way to set the token without overriding the rest of the device information such as advertisingId and model etc?

Thanks for your help

**Comment by vinicius-animo** [comment]
Hi @benjwilson10.

When `flutter_segment` sets new Context values (done in a middleware), any old value is preserved by performing a deep merge.

Unfortunately the problem resides in the official Segment library for Android, not our plugin.
The library does not add the custom `Device` if any middleware sets a new context.

[I have opened an issue in  the official library](https://github.com/segmentio/analytics-android/issues/654). I used some of your data as an example, if you don't mind.
Feel free to join with comments / reactions to grab their attention ;)

**Comment by MaiKaY** [comment]
Hi @vinicius-animo,
could you please try to reproduce it again with the latest native segment versions (https://github.com/claimsforce-gmbh/flutter-segment/commit/3757233416f71652f0af0eddbdc30bcc44d79ba7) ?

Thanks in advance.

**Comment by MaiKaY** [comment]
Hi @benjwilson10,
could you try it again with our latest version ([`2.1.0`](https://pub.dev/packages/flutter_segment))

**Comment by MaiKaY** [comment]
Close this issue due to inactivity.

**Comment by MaiKaY** [comment]
Please keep in mind for iOS its fixed with version [`2.1.1`](https://pub.dev/packages/flutter_segment).
