### ISSUE TITLE
Branch metrics analytics feature request

### ISSUE THREAD

**Issue by shashikantdurge** [claimsforce-gmbh/flutter-segment#16]
Branch metrics needs additional setup.

Can we have it in the plugin ?

**Comment by MaiKaY** [comment]
Hi @shashikantdurge,
may I ask you to create a PR since you already got the implementation in your fork?
(https://github.com/shashikantdurge/flutter-segment/commits/master)

**Comment by MaiKaY** [comment]
Available in [`2.1.0`](https://pub.dev/packages/flutter_segment)

**Comment by shashikantdurge** [comment]
This request turned out to be a bad one. Our app is rejected for using Branch SDK. Find the details here:
<img width="721" alt="Screenshot 2020-08-19 at 1 34 41 PM" src="https://user-images.githubusercontent.com/20161204/90608828-c9c23400-e220-11ea-98c4-f3894589515f.png">

**Comment by shashikantdurge** [comment]
@MaiKaY We have got the above message from google even after Disabling the Branch integration
