### ISSUE TITLE
On SegmentObserver() and recordScreenViews()

### ISSUE THREAD

**Issue by dgilperez** [claimsforce-gmbh/flutter-segment#17]
Hi! 

Many thanks for maintaing `flutter-segment`. I'm using it as an alternative to the Segment's official setup for Android. My first goal is to have the most automatic analytics as possible, so I added the `Observer` to my MaterialApp, like this: 

```
class _MyAppState extends State<MyApp> {
...
  @override
  Widget build(BuildContext context) {
    return Container(
      child: MaterialApp(
        ... 
        navigatorObservers: [
          SegmentObserver(),
        ]
        ...
      )
    )
}
```

Unfortunately, I don't see any events from that call arriving at Segment. Any ideas why? 

I also checked the official installation instructions and I see the `recordScreenViews` call: 

```
// Create an analytics client with the given context and Segment write key.
Analytics analytics = new Analytics.Builder(context, "xxx")
  // Enable this to record certain application events automatically!
  .trackApplicationLifecycleEvents()
  // Enable this to record screen views automatically!
  .recordScreenViews() <---- THIS
  .build();
```

That looks like something I'd like to activate, but looking at the source code of the package, I don't see that method being called on initialization. 

Is that method used by `flutter_segment`? If not, can I activate it somehow, or would you consider a PR to add it? 

Thanks!

**Comment by dgilperez** [comment]
Updating ... I forked, added the `recordScreenViews()` to the package and used the example app in `/example` in the emulator ... and I get debug information in Segment. Lifecycle events reach Segment as well. All is looking fine.

Using the same local package in my App (`path:` directive in the `pubspec.yml`), running it in the emulator ... and I don't see any debug information coming to Segment. Not even explicit `Segment.screen` calls. 

I do see the Debug messages in the Visual Code, in the form of 
```
D/Analytics(30615): Ran ScreenPayload{name="ping,category="null"} on integration Segment.io in 53000 ns.
```

So it clearly looks like a misconfiguration ... but I can't locate it. I followed the install instructions once and again ... 

... desperate cry for help here 🙏

**Comment by nedrocks** [comment]
I can't help you but I installed this earlier this morning in my app and noticed the same behavior in that screens are not tracked. I ended up just manually calling the `.screen()` function at the base of my stateful widget that renders the screen. It's DEFINITELY not perfect, but it gets the job done.

**Comment by dgilperez** [comment]
Thanks @nedrocks. My problem is that even `.screen()` calls are not reaching segment ... no idea why 🤷

**Comment by MaiKaY** [comment]
Hi @dgilperez,
did I understand you correctly that all methods except `.screen()` are working?

**Comment by dgilperez** [comment]
Thanks for answering @MaiKaY. I ended up finding the issue: Firebase Performance package was interfering with Segment (and also Crashlytics and other packages). Disabled the first, got this back to working. 

On the second part of the question, I still would like to benefit from the `recordScreenViews()` Segment capability (as stated in their docs). Can you clarify please if this is not needed (ie, same feature achieved through Observers, maybe?), or if this is something you'd like to add to the flutter_segment? 

Thanks a lot

**Comment by MaiKaY** [comment]
Glad to hear that you fixed the issue, @dgilperez!

To answer your question regarding `recordScreenViews()`:
As soon as you are using the `SegmentObserver()` as a `navigatorObservers` you achieved the same as you would use the native iOS implementation of `recordScreenViews()`.

**Comment by dgilperez** [comment]
Ok, thanks for the clarification!
