### ISSUE TITLE
iOS SDK Version

### ISSUE THREAD

**Issue by benjwilson10** [claimsforce-gmbh/flutter-segment#19]
Hi,

After speaking with Tech support at Segment, they have told me that in order to remove a property from a users traits with an identity call, you need to send a null value, but this is only supported on SDK versions > 3.8. After checking the version, this package using 3.7.0. Could we bump the iOS SDK version to the latest stable: 3.8.2?

This is also referenced here: https://github.com/segmentio/analytics-ios/issues/852

Thanks,
Ben

**Comment by MaiKaY** [comment]
Available in [`2.1.0`](https://pub.dev/packages/flutter_segment)
