### ISSUE TITLE
Any plans for supporting macOS?

### ISSUE THREAD

**Issue by iampawan** [claimsforce-gmbh/flutter-segment#24]
We are working on an app for macOS. Since we are already using Segment for Android & iOS, we are thinking if we can use the same for our macOS app using flutter.

**Comment by MaiKaY** [comment]
Hi @iampawan,
right now there is no plan in supporting macOS.

But if you like feel free to create it by yourself and I am more than happy to merge it into this library.

**Comment by MaiKaY** [comment]
This project is not longer maintained from this repository. In case this issue still remains please open a new issue [here](https://github.com/la-haus/flutter-library-segment/issues).
