### ISSUE TITLE
Segment-Amplitude library required when using segment with amplitude integration

### ISSUE THREAD

**Issue by gertdrui** [claimsforce-gmbh/flutter-segment#26]
As per https://developers.amplitude.com/docs/segment-amplitude-integration the client should include the separate segment-amplitude library and register amplitude's SDK in segment's SDK. 

This could be a configurable key just as with branch.io's `ENABLE_BRANCH_IO_INTEGRATION`, ie `ENABLE_AMPLITUDE_INTEGRATION`

**Comment by MaiKaY** [comment]
Available in `2.2.0`
