### ISSUE TITLE
SegmentObserver does not provide option to add properties in setScreen call

### ISSUE THREAD

**Issue by mayurdhurpate** [claimsforce-gmbh/flutter-segment#3]
In the SegmentObserver class, the `FlutterSegment.screen` method call only provides `screen` as the argument. I think `properties` can be very helpful to specify the Screen properties. 

https://github.com/claimsforce-gmbh/flutter-segment/blob/ca07508d5462d0569e2cee8296bdc3ae8c0130cd/lib/flutter_segment.dart#L129

Maybe we can use settings.arguments to provide optional `properties` to send via `FlutterSegment.screen` call?

**Comment by mayurdhurpate** [comment]
@kev52 if it's okay, I can work on a PR to add this feature. Do you think we can proceed further on this?

**Comment by MaiKaY** [comment]
Hi @mayurdhurpate,
sorry for the late response. I am currently re-working the plugin. Did you already implement something in the meantime?

**Comment by mayurdhurpate** [comment]
No, I didn't build anything yet. The feature seemed not so important to me later.
