### ISSUE TITLE
Bluetooth and cellular showing as disabled when they are enabled

### ISSUE THREAD

**Issue by conalllaverty** [claimsforce-gmbh/flutter-segment#32]
Hey,
When I send an event to Segment, the Bluetooth and cellular shows as "false" even though it is enabled. WiFi appears to be working fine. I have confirmed this across multiple different devices (Samsung and Xiaomi Android). Screenshot below.

![Screenshot 2020-08-26 at 12 18 51](https://user-images.githubusercontent.com/6192031/91297501-56776f80-e796-11ea-9a8e-b693ece25a08.png)

Any thoughts?

Cheers,
Conall

**Comment by MaiKaY** [comment]
This project is not longer maintained from this repository. In case this issue still remains please open a new issue [here](https://github.com/la-haus/flutter-library-segment/issues).
