### ISSUE TITLE
Got reject from Google after update to v2.2.2 

### ISSUE THREAD

**Issue by liemvu** [claimsforce-gmbh/flutter-segment#34]
Google had rejected my app's update because of Branch IO SDK
<img width="739" alt="Screen Shot 2020-09-07 at 9 49 52 AM" src="https://user-images.githubusercontent.com/839686/92344262-2a41e400-f0f0-11ea-9f2a-ea361de35722.png">

I found out that flutter_segment use an old version of Branch IO SDK
<img width="695" alt="Screen Shot 2020-09-07 at 9 50 41 AM" src="https://user-images.githubusercontent.com/839686/92344425-a89e8600-f0f0-11ea-9da9-90df25aeb4b8.png">

My workaround is to explicit define the newest Branch IO SDK in build.gradle:
`implementation 'io.branch.sdk.android:library:5.0.3'`

Google ok with the update, but I don't know are there any issues with flutter_segment. Please update flutter_segment to use the newest version of Branch IO SDK.

**Comment by MaiKaY** [comment]
Hi @liemvu,
we just released `3.0.0` which does not have a dependency to branch.io integration anymore which causes these issues.
If you are upgrading to `3.0.0` you should be fine.

**Comment by lolapriego** [comment]
Thanks for solving this 🙏  ! I run into the same issue
