### ISSUE TITLE
FlutterSegmentPlugin.m typo importing SEGAmplitudeIntegrationFactory.h

### ISSUE THREAD

**Issue by humberto-cetina-commure** [claimsforce-gmbh/flutter-segment#39]
Found a typo in an import statement where it should be `#import <Segment-Amplitude/SEGAmplitudeIntegrationFactory.h>` instead of `#import <Segment_Amplitude/SEGAmplitudeIntegrationFactory.h>`

**Comment by MaiKaY** [comment]
Hi @humberto-cetina-commure,
we just released a new version `3.1.3`. Could you please try and confirm that the issue is solved after upgrading to version `3.1.3`?

**Comment by RizanPSTU** [comment]
I can see this error in ^3.2.0
