### ISSUE TITLE
Missing advertisingId and adTrackingEnabled

### ISSUE THREAD

**Issue by ThangNguyen91** [claimsforce-gmbh/flutter-segment#50]
Working on debug mode and release mode but not working when upload to Testflight and Google Play for internal test
Investigate and solve the issue that Derek mentioned where the “context.device.advertisingId” and “context.device.adTrackingEnabled” parameters are not being sent to Segment.
Before upload to Google and Testflight
Android
![image](https://user-images.githubusercontent.com/28625589/104147807-68367800-5402-11eb-8494-b80c3b1b5632.png)
`"device": {
      "adTrackingEnabled": true,
      "advertisingId": "137ae789-9da4-443b-ab16-13aa7488c137",
      "id": "d2b0312831b919d3",
      "manufacturer": "Google",
      "model": "Android SDK built for x86",
      "name": "generic_x86",
      "type": "android"
    },`
iOS
![image](https://user-images.githubusercontent.com/28625589/104147857-961bbc80-5402-11eb-8ace-264a9edf34a5.png)
`"device": {
      "id": "21FF8D4A-6C80-4D4A-9C20-5E29E84B0B61",
      "manufacturer": "Apple",
      "model": "iPhone10,3",
      "name": "iPhone",
      "type": "ios"
    },`
After upload to Google and Testflight
Android
![image](https://user-images.githubusercontent.com/28625589/104147749-2dccdb00-5402-11eb-96cf-085ca8ec97c6.png)
`"device": {
      "id": "091ca52f4e020537",
      "manufacturer": "Xiaomi",
      "model": "Mi 9 SE",
      "name": "grus",
      "token": "eg-DSl2pTFOl7JG5SkDy2D:APA91bFmFFRRTCTx1RK413TG47p0OPmYXWPxX4CWgKS1QDMn3yKKhOtNlYUgApo_ZH5HVHC9gqxxW-oWIdkTt4QllUOUn9BF0ciA-hOnGLQipUAcYdR5XrF2bhVbJasaFlmIWwhKSE24",
      "type": "android"
    },`
iOS
![image](https://user-images.githubusercontent.com/28625589/104147901-c2cfd400-5402-11eb-88e5-aa9672ac0dec.png)
`"device": {
      "id": "CAA69F26-C698-4343-ADB7-3119B7F626C9",
      "manufacturer": "Apple",
      "model": "iPhone9,4",
      "name": "iPhone",
      "token": "fkx4dxtHbEEotTTR8Ses-k:APA91bGA6Pnauu_7iCaW2lyU7Q2v1f1RW_Z6KWjUixI0oBsXNMTDfizN_xPwdLf76HuZEyLg5_HYD5L3ewsDsVNl5fQAK79fWhLpQ4C-sCxyLZg6KwLBtvt6nMT9FK3Z6FIAAFprO9Jv",
      "type": "ios"
    },`
`**Flutter SDK version**
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\MSI\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0`

**Comment by MaiKaY** [comment]
@ThangNguyen91 may I ask you to try it with the latest version? We updated the SDKs recently.
