### ISSUE TITLE
added null safety (see: https://dart.dev/null-safety)

### ISSUE THREAD

**Issue by ThangNguyen91** [claimsforce-gmbh/flutter-segment#54]

**Comment by ryanheise** [comment]
I will start working on a pull request, happy to contribute.

**Comment by MaiKaY** [comment]
Hi @ryanheise,
awesome that you start to work on a PR for that.

Maybe we can find some volunteers to support you in case it comes to questions.

(cc @kev52 @fweinaug @viniciuszani)

**Comment by ryanheise** [comment]
Thanks, @MaiKaY . The questions I have will be on whether it is conceivable for a certain API to ever return null.

Just one question for now: can `getAnonymousId` ever return null in any circumstance?

**Comment by ryanheise** [comment]
We personally need this to work on iOS and I noticed the 4.x branch does not yet have the iOS implementation.

Therefore, we may end up making this null safety version for the current 3.x version (unless someone can quickly implement the iOS side for the 4.x branch? Let me know, if not, we'll do this for the 3.x version.)

It looks like the intention was to convert the old objective C code to Swift but right now it's stubs, unfortunately making this branch something we could not use currently.

**Comment by ryanheise** [comment]
I've created a pull request based on v3 as the v4 branch looks incomplete (missing the iOS implementation): #55 

In terms of my previous question on the nullability of the `getAnonymousId` return value, I've made it nullable to allow for the unknown.

**Comment by MaiKaY** [comment]
Hi @ThangNguyen91,
the latest version `3.1.0` has null safety support.

**Comment by ThangNguyen91** [comment]
Thanks for everything you do :)
