### ISSUE TITLE
We are searching main contributor(s) for this package

### ISSUE THREAD

**Issue by MaiKaY** [claimsforce-gmbh/flutter-segment#57]
Hello flutter_segment_community,
as most of you realized there isn't much going on in maintaining this package.
Unfortunately the main contributors of this package (me included) don't have any capacities left to do a maintenance which fulfills all needs from all of the users of this package.

Therefore we are searching for main contributor(s) to take over the development of this package.
In case you are interested just drop a comment on this "Issue" and we will reach out to you.

Don't hesitate to reach out to us if there are open questions.

**Comment by MaiKaY** [comment]
FYI - Maybe some of you are interested in becoming a main contributor
@viniciuszani @kev52 @shashikantdurge @jjchiw @gertdrui

**Comment by danielgomezrico** [comment]
Hi, I'm interested :)

**Comment by ariefwijaya** [comment]
@MIlhamDedi  Maybe interested 🥇

**Comment by YosafatM** [comment]
@MaiKaY  @danielgomezrico  I'm interested, recently I've got to check how it works, I've worked with Java and Dart, I know I need to learn quite a lot, but I learn fast and this seems promising and useful for the community
