### ISSUE TITLE
does not contain bitcode

### ISSUE THREAD

**Issue by ashish12s3** [claimsforce-gmbh/flutter-segment#61]
'/Users/***/Library/Developer/Xcode/DerivedData/Runner-fbzorwkeiulwbyaezsixawdhdtrx/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/****/Library/Developer/Xcode/DerivedData/Runner-fbzorwkeiulwbyaezsixawdhdtrx/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64

**Comment by danielgomezrico** [comment]
@ashish12s3 can you elaborate more your issue?

**Comment by MaiKaY** [comment]
Closed due to inactivity.
