### ISSUE TITLE
Support for Firebase Analytics

### ISSUE THREAD

**Issue by danielgomezrico** [claimsforce-gmbh/flutter-segment#65]
It would be cool to have the support for Firebase Analytics integration

**Comment by ariefwijaya** [comment]
I think we can integrate it in the segment panel Server to Server

**Comment by danielgomezrico** [comment]
@ariefwijaya can you elaborate more the idea?

**Comment by ariefwijaya** [comment]
In the segment admin dashboard, we can choose the destination of the trackers. So, whenever we track the data using segment,the segment will also forward it to the destination.

**Comment by danielgomezrico** [comment]
Thanks, I understand but for Firebase that's not an "automatic" integration, you need to add a setup in the Segment SDK running for each platform for Firebase, check this PR https://github.com/la-haus/flutter-library-segment/pull/4

**Comment by MaiKaY** [comment]
@danielgomezrico can we bring it to this library?

**Comment by danielgomezrico** [comment]
I didn't send anything because it is not clear to me how to divide the library into modules so this does not become big with all the third-party libraries
