### ISSUE TITLE
Events being triggered automatically

### ISSUE THREAD

**Issue by digocse** [claimsforce-gmbh/flutter-segment#66]
Not really an issue but I'd like to have a better understanding on some events that are being automatically triggered on our Flutter app. I couldn't find any reference explaining those and would appreciate your help.

#### Events:
- `Flutter`
- `UICompatibilityInput`
- `editing_overlay`

<h4>Events</h4>
<img src="https://user-images.githubusercontent.com/22969298/126171891-cb832354-6fcf-4827-8661-76dfb10a85d8.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/22969298/126171902-c9204751-68b0-4513-b062-a0e8abf34712.png" width="40%" height="40%">

Thanks!

**Comment by MaiKaY** [comment]
Closed due to inactivity.
