### ISSUE TITLE
Not listen Native Life cycle (Android)

### ISSUE THREAD

**Issue by RicharC293** [claimsforce-gmbh/flutter-segment#71]
I have specified the TRACK_APPLICATION_LIFECYCLE_EVENTS parameter to true but in the segment dashboard in debugger it does not reflect the life cycle events to me.

`<meta-data android:name="com.claimsforce.segment.TRACK_APPLICATION_LIFECYCLE_EVENTS" android:value="true" />`

Maybe this is because the native platform doesn't interact directly with flutter?

In no case do I have an automatic event registered.

**Comment by danielgomezrico** [comment]
I can see these events now

![image](https://user-images.githubusercontent.com/76348/136386109-b2ba9453-fe26-486c-8750-875c8130b82e.png)

**Comment by MaiKaY** [comment]
@RicharC293 are you experiencing the issue with the latest version? Feel free to reopen the issue in case the issue remains.
