### ISSUE TITLE
Web -- Event tracking doesn't work

### ISSUE THREAD

**Issue by vilorel** [claimsforce-gmbh/flutter-segment#73]
When I'm debugging all track events are recorded properly. When I'm building and deploying however nothing shows up on segment. Page views either through the observer or when recorded manually do work. So do identify calls. However I don't see any API t calls. 

I'm using the latest stable version of Flutter and the latest version of this plugin 3.1.2. Any clues?

**Comment by danielgomezrico** [comment]
As I can see the implementation of JS is not handled by this library, is that a good assumption @MaiKaY ?

I see that the example includes the segment JS sdk directly here https://github.com/claimsforce-gmbh/flutter-segment/blob/master/example/web/index.html

**Comment by MaiKaY** [comment]
@danielgomezrico unfortunately your assumption is wrong, the library does support web, you can find the implementation [here](https://github.com/claimsforce-gmbh/flutter-segment/blob/master/lib/src/segment_web.dart).

@vilorel @nvloc120 can you please double check and confirm that the `index.html` holds the necessary `<script>` tag as mentioned in the [instruction](https://github.com/claimsforce-gmbh/flutter-segment#web)?

**Comment by nvloc120** [comment]
@MaiKaY everything works fine on local, but when build and deploy to server then track API does not work, the rest still works fine on server.

**Comment by MaiKaY** [comment]
@nvloc120 could it be a ad-blocker issue? Can you please confirm that the issue remains with deactivated and/or no active ad-blocker?

**Comment by nvloc120** [comment]
@MaiKaY My browser doesn't have any ad-block extensions. Besides, I've tested with a browser that has an ad-block extension and all APIs didn't work (not only track API)
