### ISSUE TITLE
[Question] DeepMerge for Android Implementation

### ISSUE THREAD

**Issue by danielgomezrico** [claimsforce-gmbh/flutter-segment#82]
Hi Guys

What's the idea behind this deep merge?

https://github.com/claimsforce-gmbh/flutter-segment/blob/15ec6b2ab988a0628568357818474a7c8b638d61/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java#L87-L117

**Comment by MaiKaY** [comment]
This project is not longer maintained from this repository. In case this issue still remains please open a new issue [here](https://github.com/la-haus/flutter-library-segment/issues).
