### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by danielgomezrico** [claimsforce-gmbh/flutter-segment#85]
This issue will track all changes made to the repository in order to take advantage of github actions and know if a PR could be merged without breaking something:

- [x] Add action to run build for iOS, android and web https://github.com/claimsforce-gmbh/flutter-segment/pull/84
   - [x] Fix `example/` compilation for android and iOS https://github.com/claimsforce-gmbh/flutter-segment/pull/95
- [x] Add action to run tests:
   - [x] flutter tests https://github.com/claimsforce-gmbh/flutter-segment/pull/84
   - [ ] Add action to run android plugin implementation tests
   - [ ] Add action to run iOS plugin implementation tests
- [x] Linter setup:
   - [x] Add action to check linter issues https://github.com/claimsforce-gmbh/flutter-segment/pull/88
   - [x] Add some linter styling setup, so the structure of the project remains stable over time https://github.com/claimsforce-gmbh/flutter-segment/pull/88
> Maybe [linter](https://pub.dev/packages/linter) with some custom rules

**Comment by MaiKaY** [comment]
This project is not longer maintained from this repository. In case this issue still remains please open a new issue [here](https://github.com/la-haus/flutter-library-segment/issues).
