### ISSUE TITLE
Immediate crash on iOS

### ISSUE THREAD

**Issue by jeremynorman89** [claimsforce-gmbh/flutter-segment#87]
We are attempting to upgrade from 3.1 (using native initialisation) to 3.3 (dart initialisation), it worked great for Android but on iOS as soon as it launches, it crashes immediately with the following error:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1a30ff25c 0x1b6e94480 0x1a316aab4 0x1a3175bf4 0x1a2ff8dc8 0x1a2fec118 0x104af52f8 0x104af50a8 0x104af59dc 0x104b053d8 0x1a2d362b0 0x1a2d37298 0x1a2cdfa40 0x1a2ce0518 0x1a2ce9fac 0x1eb6315bc 0x1eb63486c)
libc++abi: terminating with uncaught exception of type NSException
* thread #3, queue = 'io.segment.analytics', stop reason = signal SIGABRT
    frame #0: 0x00000001cef657b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1cef657b0 <+8>:  b.lo   0x1cef657cc               ; <+36>
    0x1cef657b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1cef657b8 <+16>: mov    x29, sp
    0x1cef657bc <+20>: bl     0x1cef421fc               ; cerror_nocancel
Target 0: (Runner) stopped.
```

This happens before any code to provide a write key or anything is executed.

**Comment by MaiKaY** [comment]
@esarbanis, do you have an idea why this could happen?

**Comment by Vukan-Markovic** [comment]
Got the same problem when trying to run with version 3.3.0

**Comment by esarbanis** [comment]
@MaiKaY @ariefwijaya I have the fix in a PR.

Although in #49 I tested the backward compatibility, I didn't properly test the case where a file configuration is not present in iOS :disappointed:.

I have properly tested this in our app, as we added segment support and it was a good opportunity to fix this as well :slightly_smiling_face:

**Comment by HerrNiklasRaab** [comment]
Maybe pin this issue till its fixed? Just ran into it as well!

**Comment by MaiKaY** [comment]
We just released `3.4.0` to fix this issue.

**Comment by JobGetabu** [comment]
the update causes:
`[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (Segment-Amplitude)`

It could resolve if I remove 
`use_frameworks!` from my `Podfile`
But I need `use_frameworks!`

**Comment by esarbanis** [comment]
@JobGetabu I don't think that this error is relevant to this issue. 

Can you please open up a new issue, so we don't confuse the 2? :pray:

**Comment by HerrNiklasRaab** [comment]
@esarbanis I have the same issue

**Comment by nmarko91** [comment]
> @JobGetabu I don't think that this error is relevant to this issue.
> 
> Can you please open up a new issue, so we don't confuse the 2? 🙏

I opened a new one for this, to make things easier https://github.com/claimsforce-gmbh/flutter-segment/issues/96
